name: R. Ilham Sastronegoro
slogan: Web Developer from Sampit, Indonesia
description: >-
  Personal website of R. Ilham Sastronegoro,
  web developer from Sampit, Kalimantan Tengah, Indonesia.
  He focused in JAMstack and modern web technology.
menu:
  - name: Home
    path: /
  - name: About
    path: /about
  - name: Work
    path: /work
  - name: Contact
    path: /contact
