name: Latest blog posts
on:
  schedule: # Run workflow automatically
    - cron: '10 1/6 * * *' # Runs every 6 hour beginning 1.10 UTC
  workflow_dispatch # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://sngrdev.hashnode.dev/rss.xml"