name: Build on README edit
on:
  push:
    branches:
      - 'main' 
  schedule:
    - cron: '40 17 * * *'
  workflow_dispatch:
  
jobs:
  build:
    name: Build on README edit
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}