name: Build on README edit
on:
  push:
    branches:
      - 'main' 
jobs:
  build:
    name: Build on README edit
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}